### ISSUE TITLE
[DEP0180] DeprecationWarning: fs.Stats constructor is deprecated in Node v22.0.0

### ISSUE THREAD

**Issue by IronGeek** [wooorm/import-meta-resolve#27]
Hi, I received a deprecation warning when running babel using node v22.0.0.  
And based on the error message, it seems the warning originated from the `import-meta-resolve` package babel is using:

```js
(node:241428) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at tryStatSync (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:511:12)
    at packageResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:889:18)
    at moduleResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPlugin (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at loadPlugin.next (<anonymous>)
    ...
```

Apparently calling `fs.Stats` class directly with `Stats()` or `new Stats()` is being [deprecated in node v22.0.0](https://nodejs.org/api/deprecations.html#DEP0180):

https://github.com/wooorm/import-meta-resolve/blob/66b952bed052575a0ea44b71e90b4c4c87368071/lib/resolve.js#L134-L141

**Comment by wooorm** [comment]
Well, this is internals...

**Comment by IronGeek** [comment]
I kinda figure it out... I guess this issue a bit of an edge cases...

1. You need to be using `Node v22`.
2. You need to be using `pnpm`.
   Tested with `npm` and `pnpm`. The deprecation warning is not shown with `npm`. I guess its related to how `pnpm` treats and resolve transitive dependencies (see point 3, below).
3. You need to be using a babel presets or plugins that are not directly added as dependency

For example, running:
```bash
pnpm add -D @babel/cli @babel/core @babel/preset-env
touch index.js
pnpm exec babel index.js -d out --presets=@babel/preset-env --plugins=@babel/plugin-transform-class-properties
```
will result in success (kinda) but with a warning.:
```bash
(node:279128) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Successfully compiled 1 file with Babel (416ms).
```

While installing the dependencies using `npm` and running with `npx` will result in:
```bash
npx babel index.js -d out --presets=@babel/preset-env --plugins=@babel/plugin-transform-class-properties
Successfully compiled 1 file with Babel (327ms).
```

Both commands are using the `@babel/plugin-transform-class-properties` plugin, a transitive dependency from `@babel/preset-env`. While `NPM` can resolve it just fine, `pnpm` can't.

But, if we try to use a preset or a plugin that are not installed at all; like `@babel/preset-react` for example, both `pnpm` and `npm` will result in error:

```bash
pnpm exec babel index.js -d out --presets=@babel/preset-env,@babel/preset-react --plugins=@babel/plugin-transform-class-properties
(node:280601) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Cannot find package '@babel/preset-react' imported from <REDACTED>/babel-virtual-resolve-base.js
    at __node_internal_ (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:224:9)
    at new NodeError (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPreset (<REDACTED>/node_modules/.pnpm/@babel+core@7.24.4/node_modules/@babel/core/lib/config/files/plugins.js:61:20)
    at loadPreset.next (<anonymous>)
...
```

```bash
npx babel index.js -d out --presets=@babel/preset-env,@babel/preset-react --plugins=@babel/plugin-transform-class-properties
(node:280117) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Cannot find package '@babel/preset-react' imported from <REDACTED>/babel-virtual-resolve-base.js
    at __node_internal_ (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:224:9)
    at new NodeError (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (<REDACTED>/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (<REDACTED>/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (<REDACTED>/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (<REDACTED>/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPreset (<REDACTED>/node_modules/@babel/core/lib/config/files/plugins.js:61:20)
    at loadPreset.next (<anonymous>)
...
```

**Comment by wooorm** [comment]
This *is* happening here on Node 22. You can run the tests and see it.

**Comment by wooorm** [comment]
done!
